// Code generated by simplesql. DO NOT EDIT.

package repo

import (
	"context"
	"strings"

	"github.com/cockroachdb/errors"
	"github.com/index0h/simplesql/querier"
)

type userRepositoryImpl struct {
	cm *querier.ConnectionManager
}

func NewUserRepository(cm *querier.ConnectionManager) *userRepositoryImpl {
	return &userRepositoryImpl{cm: cm}
}

func (s *userRepositoryImpl) FindById(ctx context.Context, id int) (*User, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT u.id, u.name, u.enabled FROM users u\nLEFT JOIN balances b ON b.user_id = u.id\nWHERE u.id = ?\n")
	_args = append(_args, id)
	if id > 1000 {
		_sb.WriteString(" AND u.id > 1000")
	}
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_rows, _err := _db.QueryContext(ctx, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	defer _rows.Close()
	_cols, _err := _rows.Columns()
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	if !_rows.Next() {
		return nil, nil
	}
	var _dest User
	_ptrs, _err := querier.FieldPointers(&_dest, _cols)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	_err = _rows.Scan(_ptrs...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return &_dest, nil
}

func (s *userRepositoryImpl) FindAll(ctx context.Context, enabled *bool, minId *int) ([]*User, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT * FROM users WHERE 1=1\n")
	if enabled != nil {
		_sb.WriteString(" AND enabled = ?")
		_args = append(_args, enabled)
		if minId != nil {
			_sb.WriteString(" AND id > ?")
			_args = append(_args, minId)
		}
	} else if minId != nil {
		_sb.WriteString(" AND id > ?")
		_args = append(_args, minId)
	}
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_rows, _err := _db.QueryContext(ctx, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	var _result []*User
	_err = querier.ScanRows(_rows, &_result)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return _result, nil
}

func (s *userRepositoryImpl) SelectColumns(ctx context.Context, cols string) ([]*User, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT ")
	_sb.WriteString(cols)
	_sb.WriteString(" FROM users ORDER BY id")
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_rows, _err := _db.QueryContext(ctx, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	var _result []*User
	_err = querier.ScanRows(_rows, &_result)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return _result, nil
}

func (s *userRepositoryImpl) FindAllValues(ctx context.Context) ([]User, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT * FROM users ORDER BY id")
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_rows, _err := _db.QueryContext(ctx, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	var _result []User
	_err = querier.ScanRows(_rows, &_result)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return _result, nil
}

func (s *userRepositoryImpl) Create(ctx context.Context, name string, enabled bool) (int, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("INSERT INTO users (name, enabled) VALUES (?, ?)")
	_args = append(_args, name)
	_args = append(_args, enabled)
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_res, _err := _db.ExecContext(ctx, _query, _args...)
	if _err != nil {
		return 0, errors.WithStack(_err)
	}
	_id, _err := _res.LastInsertId()
	return int(_id), errors.WithStack(_err)
}

func (s *userRepositoryImpl) UpdateEnabled(ctx context.Context, id int, enabled bool) (int, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("UPDATE users SET enabled = ? WHERE id = ?")
	_args = append(_args, enabled)
	_args = append(_args, id)
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_res, _err := _db.ExecContext(ctx, _query, _args...)
	if _err != nil {
		return 0, errors.WithStack(_err)
	}
	_n, _err := _res.RowsAffected()
	return int(_n), errors.WithStack(_err)
}

func (s *userRepositoryImpl) DeleteById(ctx context.Context, id int) (int, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("DELETE FROM users WHERE id = ?")
	_args = append(_args, id)
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_res, _err := _db.ExecContext(ctx, _query, _args...)
	if _err != nil {
		return 0, errors.WithStack(_err)
	}
	_n, _err := _res.RowsAffected()
	return int(_n), errors.WithStack(_err)
}

func (s *userRepositoryImpl) Rename(ctx context.Context, id int, name string) error {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("UPDATE users SET name = ? WHERE id = ?")
	_args = append(_args, name)
	_args = append(_args, id)
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_, _err := _db.ExecContext(ctx, _query, _args...)
	return errors.WithStack(_err)
}

func (s *userRepositoryImpl) FindByIdSync(id int) (*User, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT * FROM users WHERE id = ?")
	_args = append(_args, id)
	_query := _sb.String()

	_db := s.cm.DB(context.Background())
	_rows, _err := _db.QueryContext(context.Background(), _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	defer _rows.Close()
	_cols, _err := _rows.Columns()
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	if !_rows.Next() {
		return nil, nil
	}
	var _dest User
	_ptrs, _err := querier.FieldPointers(&_dest, _cols)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	_err = _rows.Scan(_ptrs...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return &_dest, nil
}

func (s *userRepositoryImpl) FindWithBalance(ctx context.Context, id int) (*UserBalance, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT u.id, u.name, u.enabled, b.user_id, b.amount FROM users u\nINNER JOIN balances b ON b.user_id = u.id\nWHERE u.id = ?")
	_args = append(_args, id)
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_rows, _err := _db.QueryContext(ctx, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	defer _rows.Close()
	_cols, _err := _rows.Columns()
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	if !_rows.Next() {
		return nil, nil
	}
	var _dest UserBalance
	_ptrs, _err := querier.FieldPointers(&_dest, _cols)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	_err = _rows.Scan(_ptrs...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return &_dest, nil
}

func (s *userRepositoryImpl) ListWithBalances(ctx context.Context) ([]*UserBalance, error) {
	var _sb strings.Builder
	var _args []any
	_sb.WriteString("SELECT u.id, u.name, u.enabled, b.user_id, b.amount FROM users u\nINNER JOIN balances b ON b.user_id = u.id\nORDER BY u.id")
	_query := _sb.String()

	_db := s.cm.DB(ctx)
	_rows, _err := _db.QueryContext(ctx, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	var _result []*UserBalance
	_err = querier.ScanRows(_rows, &_result)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return _result, nil
}
