CREATE TABLE IF NOT EXISTS users (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    name    TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS balances (
    user_id INTEGER NOT NULL REFERENCES users (id),
    amount  INTEGER NOT NULL DEFAULT 0
);
