package internal

import "text/template"

var headerTmpl = template.Must(template.New("header").Parse(`// Code generated by simplesql. DO NOT EDIT.

package {{.Package}}

import (
{{.Imports}})
`))

var structTmpl = template.Must(template.New("struct").Parse(`
type {{.StructName}} struct {
	cm *simplesql.ConnectionManager
}

func New{{.InterfaceName}}(cm *simplesql.ConnectionManager) *{{.StructName}} {
	return &{{.StructName}}{cm: cm}
}
`))

// selectOneTmpl names its error return so the deferred close can join _rows.Close()'s
// error into whatever the method is already returning, instead of discarding it.
// errors.Join (not CombineErrors) matters here: CombineErrors attaches the second error
// as a "secondary" that's invisible to both Error() and errors.Is/As — Join gives a real
// multi-error via Unwrap() []error, so the close error is actually observable.
var selectOneTmpl = template.Must(template.New("selectOne").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) (_ *{{.ReturnType}}, _err error) {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	_rows, _err := _db.QueryContext({{.ContextExpr}}, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	defer func() {
		_err = errors.Join(_err, _rows.Close())
	}()
	_cols, _err := _rows.Columns()
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	if !_rows.Next() {
		if _err := _rows.Err(); _err != nil {
			return nil, errors.WithStack(_err)
		}
		return nil, nil
	}
	var _dest {{.ReturnType}}
	_ptrs, _err := simplesql.FieldPointers(&_dest, _cols)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	_err = _rows.Scan(_ptrs...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return &_dest, nil
}
`))

// selectManyTmpl renders []*T or []T depending on ReturnIsPtr; simplesql.ScanRows determines
// which one it was scanning into via reflection on _result's declared element type, so no
// other part of this template needs to change between the two.
var selectManyTmpl = template.Must(template.New("selectMany").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) ([]{{if .ReturnIsPtr}}*{{end}}{{.ReturnType}}, error) {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	_rows, _err := _db.QueryContext({{.ContextExpr}}, _query, _args...)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	var _result []{{if .ReturnIsPtr}}*{{end}}{{.ReturnType}}
	_err = simplesql.ScanRows(_rows, &_result)
	if _err != nil {
		return nil, errors.WithStack(_err)
	}
	return _result, nil
}
`))

var insertIDTmpl = template.Must(template.New("insertID").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) (int, error) {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	_res, _err := _db.ExecContext({{.ContextExpr}}, _query, _args...)
	if _err != nil {
		return 0, errors.WithStack(_err)
	}
	_id, _err := _res.LastInsertId()
	return int(_id), errors.WithStack(_err)
}
`))

// insertIDReturningTmpl is used instead of insertIDTmpl for Postgres, which has no
// LastInsertId() equivalent. CompileBody appends "RETURNING id" to the query text for
// this case (see compiler.go), so the id is read back via QueryRowContext+Scan instead.
var insertIDReturningTmpl = template.Must(template.New("insertIDReturning").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) (int, error) {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	var _id int
	_err := _db.QueryRowContext({{.ContextExpr}}, _query, _args...).Scan(&_id)
	return _id, errors.WithStack(_err)
}
`))

var execRowsTmpl = template.Must(template.New("execRows").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) (int, error) {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	_res, _err := _db.ExecContext({{.ContextExpr}}, _query, _args...)
	if _err != nil {
		return 0, errors.WithStack(_err)
	}
	_n, _err := _res.RowsAffected()
	return int(_n), errors.WithStack(_err)
}
`))

var execErrTmpl = template.Must(template.New("execErr").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) error {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	_, _err := _db.ExecContext({{.ContextExpr}}, _query, _args...)
	return errors.WithStack(_err)
}
`))

var execVoidTmpl = template.Must(template.New("execVoid").Funcs(helperFuncs).Parse(`
func (s *{{.StructName}}) {{.MethodName}}({{paramList .Params}}) {
{{.QueryBody}}
	_db := s.cm.DB({{.ContextExpr}})
	_, _ = _db.ExecContext({{.ContextExpr}}, _query, _args...)
}
`))
